name: Defold

on: [push, pull_request]

jobs:
  defold:
    name: ${{ matrix.platform }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        platform: [x86_64-linux, js-web]

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: "25"
          distribution: "temurin"

      - name: Setup Defold
        uses: dapetcu21/setup-defold@v3.0.3

      - name: Setup Lua
        uses: leafo/gh-actions-lua@v12
        with:
          luaVersion: "5.4"

      - name: Setup LuaRocks
        uses: leafo/gh-actions-luarocks@v6
        with:
          luaRocksVersion: "3.13.0"

      - name: Install luapit
        run: |
          luarocks install busted
          luarocks install penlight
          luarocks install luamark
          luarocks install argparse --dev
          luarocks install dkjson
          luarocks install chronos
          luarocks install https://raw.githubusercontent.com/lunarmodules/terminal.lua/refs/heads/main/terminal-scm-1.rockspec
          luarocks make

      - name: Setup Node.js
        if: matrix.platform == 'js-web'
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install Playwright
        if: matrix.platform == 'js-web'
        run: |
          npm install playwright
          npx playwright install chromium

      - name: Run Defold desktop integration test
        if: matrix.platform == 'x86_64-linux'
        timeout-minutes: 10
        run: luapit ref . -R defold -b tests/engines/fixtures/ -t

      - name: Run Defold HTML5 integration test
        if: matrix.platform == 'js-web'
        timeout-minutes: 10
        run: luapit ref . -R defold-html5 -b tests/engines/fixtures/ -t
